### ISSUE TITLE
Not opensource - mostly dlls

### ISSUE THREAD

**Issue by winecraft** [optimajet/DWKit#1]
We have a need and began trying this. I would be interested in trying this solution, but when I pull down and build in VS 2013 I get errors on tamper/late signing in DLL's etc.

So when I check the code - most of the code in DW kit has only DLL's and no source - <h4> Can you confirm this is an open source project. </h4>
Can you also share the steps to setup.

**Comment by dmelnikov** [comment]
Many part of the project is open source, but not full.

What errors did you have?

**Comment by winecraft** [comment]
A few besides the warnings, JS warnings errors/warning are plenty as well I could help more her. But I cant see any of the JS code either to to step through or cleanup. I wanted to try it various providers, but it was easy to switch out - if this was an option in the designer/UI it would be nice.

Anyways, in the errors, I get Object set to null reference, <b>there are many objects in your name space that have null references.</b> and because its closed source and not open source I cannot even debug that either!

**Comment by winecraft** [comment]
BTW this is <h2>NOT AN OPEN SOURCE PROJECT</h2> it should not be on github

**Comment by dmelnikov** [comment]
Do you need help with this or you want continue dialog about available full source code or just part?
