### ISSUE TITLE
Problem running it on net6.0

### ISSUE THREAD

**Issue by sedsajad720** [optimajet/DWKit#158]
Hello.

I have a problem running the `Starter Pack 3.6.0` file on my localhost. I downloaded the zip file, ran the sql files according to the `readme.text`, changed the connection string, ran `npm install`, all according to the documentation. But when I run the app from Visual Studio 2022 using `IIS Express`, I get the following error:

_**TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Features.IHttpSendFileFeature' from assembly 'Microsoft.AspNetCore.Http.Features, Version=6.0.0.0**_

When I checked the DWKit-Core package, I noticed that inside it, there is the `Microsoft.AspNetCore.Http.Features` package (version 5.0.17), but according to the microsoft official documentation, the `IHttpSendFileFeature` has been deprecated after net5.0.

Do you also think that this is causing the problem? Or is there something else that is causing the problem?

Any answer would be much appreciated, thank you in advance.

**Comment by optimajet** [comment]
This request will be closed, as the discussion is already underway in the internal issue tracker.
