### ISSUE TITLE
Not working with nuget update - unable to debug (IS THIS REALLY OPEN SOURCE OR NOT)

### ISSUE THREAD

**Issue by patagoniahiker** [optimajet/DWKit#3]
After I updated to latest ASP via Nuget, the sample stopped working.

Here are some items that were confusing.
-  How do you bind the user to ASP Identity to get the user role - can you post a code sample and explain where this should happen
1. Where are the options on the budget items from the designer, 
2. Why does it only shows change manager options
3.  For small shops how can I get rest of the roles to same user, is there a role creating/assignment tab or option?

Can you post a snippet on how to activate or manage those roles and reverse/correct any user actions

**Comment by dmelnikov** [comment]
Your questions is not clear for me.
Please, read the documentation - http://dwkit.com/Documentation

After that I'm ready help you. Please, write to dwkit@optimajet.com with more information about your company and your project.

**Comment by patagoniahiker** [comment]
I am asking about the various roles, for e.g. app rovers, users, managers etc. How are all those members configured and managed in this?

Next, I was asking how are actions performed on a pending work item

I am not a company, just an developer trying out the this to see if it might be a fit for someone I am helping. If you can answer some of this, I can shoot you some questions.

**Comment by dmelnikov** [comment]
About the security model:
- http://dwkit.com/Documentation/detail/Security
- http://dwkit.com/Documentation/detail/dbstructsec
- http://dwkit.com/Documentation/detail/Workflow

What is work item? This sample has BudgetItem's element only.

DWKIT don't free for commercial use. If your customer is commercial company then they must get a license. Please, write to dwkit@optimajet.com for get the license.

**Comment by patagoniahiker** [comment]
Finally some information, thanks for the links, I meant budget item, (generically speaking/work item). 
FYI - I am not commercial. 

* Restoring in the DB 2014 or MySql gives me error, I am trying with change compatibility levels. I only have express version now, and my Sql Developer is a trial expiring in 2 months.
* BTW - there is no price listed on your price page.
* Does this work with Membership that comes with ASP Identity 2.2, or is this a completely separate model, how can I link the users between the two?
* <h6>Why is it asking for a commercial license key - is this not open source? </h6> How am I supposed to try it.
`Dynamicentitysettings...RegisterLicense("Add you key DW KIT");
 Core.Runtime.Workflow...registerLicense("Add your key WF");`
* Where exactly are the budget items created, are they the same as a business object? 
* Where are the new users added/setup?
* What base object does `budget item` inherit from?
* Should I override the behavior, add a new function, or create a new class, when I want some other functionality (for e.g. I want to add a check image to the budget item)
* How can the budget item be moved to the next stage, and what class preforms this operations on the budget item
* can you show snippets on handling budget items for the above?

**Comment by dmelnikov** [comment]
You don't have the support contract therefore I can offer you study the documentation: http://dwkit.com/Documentation
The documentation have almost answers.

If you don't have a license key then you can use with some limits by count of objects.

**Comment by patagoniahiker** [comment]
Reminds me of a shady car salesman!
Never answer to the questions, in the previous post you said "*Your questions is not clear for me*" and now you want me to buy a license to get the answers.

**You should disclose & list on the main page and wiki **-- no support available, purchase required!

**Comment by dmelnikov** [comment]
Not, I offer you learn the documentation yourself.
