### ISSUE TITLE
Out of date, does not work

### ISSUE THREAD

**Issue by sergy79** [optimajet/DWKit#4]
Was this even tested, it does not work on VS community edition, I think the main issue is the runtime, since it does not support this version in your project.

Look here http://getdotnet.azurewebsites.net/target-dotnet-platforms.html

**Comment by dmelnikov** [comment]
May be. We didn't test on VS Community edition.

**Comment by sergy79** [comment]
Ok I was able to upgrade and resolve myself thanks :-)
