### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sergy79** [optimajet/DWKit#5]
Hi when will this be updated?

**Comment by dmelnikov** [comment]
Next update will be coming soon about 3-4 weeks.

**Comment by sergy79** [comment]
I wanted to check in, can you please update this... I can not get it to work with the current versions of WFE

**Comment by dmelnikov** [comment]
What a problem with the current version?

**Comment by sergy79** [comment]
SubscribeOnDynamic is timing out. Then I write my own subscription class/event after trying SubscribeOnDynamicEntityNotifications , yet I did not get user notification on BudgetItemUpdates or document update. Optima website explain execute command good but the document or budget item updates notifications help or diagram is not there or a simple explain with code sample.

When I do some debugging and step-in some of the persistence change states during notification or add to inbox throw exception... I found DocumentAddToInbox or when trying  NotificationWorkflowMyDocChangeState - when I look inside I find that Workflow .DbPersistence  and  Process Scheme etc have changed. Now I stop and wait for update, because I do not want to touch WFE changes.

I hope this is of help, I have some more but I believe they all have common problem, please update and share some views on whats happen.

**Comment by dmelnikov** [comment]
I can't reproduce it.
Please, make a backup of your DB and send it to dmelnikov@optimajet.com.
I review it.

**Comment by sergy79** [comment]
can you update this to work with current WFE please

**Comment by dmelnikov** [comment]
No, I can't. 
We have no any decision about which the part of DWKIT/WFE will be published on GitHub.

These products are commercial. All materials (without the license) can use for education only.
If you're using a part of these for commercial activities you're breaching the rules of license.

I hope you understand it and your customers will be no problems in the future.

**Comment by sergy79** [comment]
Alright thanks, I did not realize that, I thought this was open source, kind of misleading if you ask me.

**Comment by dmelnikov** [comment]
Open source software != free software

**Comment by sergy79** [comment]
It must at least be _working _versions right    :-1:
