### ISSUE TITLE
is this really open source, old abondoned and does not work if I update with Nuget

### ISSUE THREAD

**Issue by mach37** [optimajet/DWKit#6]
Hi, I am looking for some opensource for document approval and found your dwkit, But this seems abandoned and old. My curiosity is, since I have not seen any updates, and when I try it with this with the updates in nugets it does not work any longer.

Mainly I am looking for something like this https://github.com/mrsalmon1976/Stateless.WorkflowEngine , https://github.com/akarpov89/MicroFlow , https://github.com/uname-yang/WorkFlow-Engine-OData-WebApi-with-OdataClient

This also working beautifully but its WF - https://github.com/orosandrei/Rehosted-Workflow-Designer
your is not working like this

**Comment by dmelnikov** [comment]
DWKIT is a different product. It's a platform. Stateless, MicroFlow and etc. is just a workflow engine. 
May do you have any technical or commercial questions?

**Comment by mach37** [comment]
So is this dockument kit different not based on workflow server.

Where is there a help guide for that. for e.g. in Window WF and Nworkflow its easy to configure the workflow, how can I do this with the meta workflow, can I copy that workflow or do I need to redo everything from beginning. 

When I add this to the workflow sample with Nuget it breaks, check/test compile with the other worflow dll's. The description and pictures are nice, but its very hard to get working or understand.

**Comment by dmelnikov** [comment]
Do you have a license of DWKIT/WFE for commercial use?

**Comment by dmelnikov** [comment]
If no, please, send a order to sales@optimajet.com for presale support.
